wb:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: wb_ai
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tRSrCtJCn3gicN18qbn
    access-key-secret: Axr6qrlzFIjO3FOQqnuqvoeQFa8SlF
    bucket-name: wb-take-out-cwj333
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: wb1
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: wb2
    user-ttl: 7200000
    # user-token-name: token
    # 前端发送请求时需要使用这个作为请求头中的参数名而非token，方便local storage同时存储2种不同账号的令牌
    user-token-name: authentication
deepseek:
  api:
    token: sk-36a7886474a44be7bd9ac95fabf9b08f
